version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'eduflow'
      MYSQL_USER: 'root'
      MYSQL_USER_PASSWORD: 'eduflow'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
